### ISSUE TITLE
 telegram-openai-assistant run

### ISSUE THREAD

**Issue by vassilevev** [efelem/telegram_openai_assistant#1]
When I try to start it I get this error, the installation went through without errors. How to fix?
Sorry, my level of knowledge is near the baseboard.

Traceback (most recent call last):
  File "/usr/bin/chatbot", line 33, in <module>
    sys.exit(load_entry_point('telegram-openai-assistant', 'console_scripts', 'chatbot')())
  File "/usr/bin/chatbot", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: telegram-openai-assistant

**Comment by efelem** [comment]
Just updated the code. It now supports multibots :). I am closing this. Feel free to open a new issue if this does not work @vassilevev
